### ISSUE TITLE
Resources not loading

### ISSUE THREAD

**Issue by maxolasersquad** [linappleii/linapple#10]
The resources where moved to the `res/` directory in bbc0fbf8837bb7e445688908b0df9b8e5475526e.  When linapple executes it generates the following errors.

```
Video: ./splash.bmp was not loaded
Video: Apple text is not available: ./charset40.bmp was not loaded
```

I've tried setting `RESOURCE_DIR` in `Resources.h` to `./res/`, `res/`, and `/res/`. The only thing that worked was setting the fully qualified path to where I have the project cloned, but that's obvious a no-go.

Since the application cannot even load the font then nothing shows up on the screen.

**Comment by iKarith** [comment]
You're running it without make install?

**Comment by maxolasersquad** [comment]
I only ran `make` and then `bin/linapple`.
