### ISSUE TITLE
Apple II/IIplus emulation and master.dsk

### ISSUE THREAD

**Issue by ThorstenBr** [linappleii/linapple#101]
This is what happens when you load master.dsk with the emulator in Apple II/IIplus mode:
![AppleIIplus_master_dsk](https://user-images.githubusercontent.com/51717934/76307125-84402900-62c8-11ea-8427-86e2f5d52367.png)

I was worried my video ROM updates had broken something. But it's always been this way. Same for current AppleWin. I knew the Apple II/IIplus had no support for lowercase letters, but I always thought it would just display uppercase letters instead. That's obviously not the case: the lowercase letters are mapped to completely mismatching letters.

I only have an Apple IIe, not an actual Apple II to verify the correct behaviour. Is this really how things were? So even simple basic programs using lowercase letters (developed on a IIe) couldn't run on an Apple II? Or is the emulation broken here?

If that's really how things were, it might be a good idea to adapt master.dsk (to use uppercase letters, at least when detecting a II/IIplus machine).

**Comment by whscullin** [comment]
This is really how it was. I don't have a CFFA in my plus ATM for screen shot, but it matches my recollection, and I would definitely consider it worth either detecting or going to all uppercase for the master disk.

**Comment by ThorstenBr** [comment]
So, not everything was perfect in "the good old days" then... ;-)

**Comment by whscullin** [comment]
IT WAS FINE.

**Comment by rhaleblian** [comment]
It's perfectly broken.

**Comment by rhaleblian** [comment]
Can this close?

**Comment by rhaleblian** [comment]
I still feel that way.  A nice blast into the past.
