### ISSUE TITLE
Adding a debugger to LinApple

### ISSUE THREAD

**Issue by ThorstenBr** [linappleii/linapple#105]
Hope you're all doing well these days... In a quest to do something useful during the current "corona lockdown" over here, I went along and borrowed AppleWin's debugger sources and ported them to Linux. :) This extends LinApple with a neat debugger/assembler/disassembler...

Apart from the usual VisualStudio vs GNU/Linux/SDL issues, it mainly involved replacing the character generator. I reused the same bitmap we're already using for the Apple II fonts.
Some changes were also necessary in other modules, e.g. to provide the debugger with access to video modes and memory bank information. Several variables, flags and functions had to be exposed to the header files. Those changes are mostly similar or even completely identical to current AppleWin's head - so those changes are not really new inventions.

Also, several changes were necessary to the existing Debug header files: these files were already present in LinApple, though so far mostly unused. Several debugger data structures were extended or renamed since LinApple was forked, so a number of updates were necessary to work with the latest AppleWin debug cpp sources.

All debugger sources live in a separate sub directory (src/Debugger), so debugger/assembler/disassembler sources don't clutter the rest of the emulator. This, also, is identical to the way AppleWin handles this. Exceptions are the already existing debug header files (Debug.h/Debug_Types.h), which were already present in LinApple's "inc/" folder. I left them in the global include directory - since they are included by other sources, outside the debugger itself.

Not surprisingly, the look and features are (almost) identical to AppleWin, of course. I'm still testing and playing with it, but it seems pretty stable to me. If you're interested, you can peek and test the debugger over here:
https://github.com/ThorstenBr/linapple/commits/debugtest

Press "F7" to enter debug view at any time. It should look like the screenshot below...

Obviously it'd be cool to eventually have the debugger as part of standard LinApple. I can clean up and eventually create a pull request when it's ready. Adding the debugger is a larger patch though, so let me know what you think about it...

Stay safe and healthy!

![LinAppleDebugger](https://user-images.githubusercontent.com/51717934/77800116-67507780-7076-11ea-88be-303d22bb3fef.png)

**Comment by ghedger** [comment]
This is a **substantial** value-added feature, one I would use on my own work. 

Keep us apprised of the progress.  I will test and merge as soon as you have something you're happy with.

**Comment by ThorstenBr** [comment]
Pushed merge request #108. I'll probably have a few more updates for the debugger some time later, but the debugger is already working quite well, so ready to be used and tested.
I was trying to be careful to not break anything existing. Let me know if you still noticed any issues...

**Comment by ghedger** [comment]
This debugger rocks, and you completed it rapidly.  Merged.

Good work!

**Comment by ThorstenBr** [comment]
Closed the issue for now.
Let me know when something wasn't right...
