### ISSUE TITLE
Use XDG standard for user configuration directory

### ISSUE THREAD

**Issue by maxolasersquad** [linappleii/linapple#11]
Currently the user specific configuration files are stored in `~/linapple`. An easy way to keep cruft out of the user's home directory would be to store it in `~/.linapple` instead, but the truly elegant solution is to use the [XDG spec](https://freedesktop.org/wiki/Specifications/basedir-spec/).

**Comment by maxolasersquad** [comment]
This should probably be a separate issue, but the user-specific data file directory should probably initialized when the application is run, not during the `make` process.

**Comment by iKarith** [comment]
SDL2 wants to throw everything into .local under the assumption that XDG says .config is for config files only.  That's fair and reasonable, but of course I've put SDL2 on hold until other messes are cleaned up.  So what I think I'll do is grab the requisite code from SDL2, given that it's fairly independent of the rest of SDL, and drop it in.  This is very much desired though.
