### ISSUE TITLE
RESOURCE_INIT_DIR unused?

### ISSUE THREAD

**Issue by 0cjs** [linappleii/linapple#113]
It looks to me as if `RESOURCE_INIT_DIR` is unused. The only place this is mentioned is in the Makefile, which defaults it to `/etc/linapple` and adds `-DRESOURCE_INIT_DIR=\"$(RESOURCE_INIT_DIR)\"` to the `CFLAGS`. No source code files ever reference `RESOURCE_INIT_DIR` as far as I can tell.

Is this old code that can be removed?

**Comment by rhaleblian** [comment]
In #119 I left it in there but it does nothing. I think youre right.

**Comment by 0cjs** [comment]
> In #119 I left it in there but it does nothing.

I did a bit of further research, and it looks like it kinda duplicates `ASSET_DIR`, too. Anyway, I think it's best removed for the moment, especially since you're reworking the build system, and if you see a need for something in addition to `ASSET_DIR` in your future work you can add whatever you need in a more suitable way.

**Comment by rhaleblian** [comment]
Sounds good, I see the PR.
There has been positive movement here for adopting the XDG (Freeedesktop?) guidelines configuring resources; a best outcome would be that these things fall nicely into that paradigm.

**Comment by maxolasersquad** [comment]
That work began, I believe, in https://github.com/linappleii/linapple/pull/53 and there has been more efforts since then to clean up the build process. Once the build process and code has been spruced up a bit more I think it would be a good idea to tag a new stable branch and then start a more structured process with regular releases, proper version numbering, etc.

**Comment by 0cjs** [comment]
> There has been positive movement here for adopting the XDG (Freeedesktop?) guidelines for placing and discovering resources

Yes, I am _totally_ up with that.

**Comment by rhaleblian** [comment]
Ok, we made this one closable.
