### ISSUE TITLE
Font in Apple II+ problem with charset

### ISSUE THREAD

**Issue by ghost** [linappleii/linapple#115]
After compiling this version, I have a problem with the display font while using the Apple ][+ rom.
The flash text style has a problem with the characters @ and A-O which correspond with the first row the charset40.bmp if that helps. While this wouldn't normally be an issue as not much uses flash text, Wizardry however does somehow access these characters to display normal text. 

Here is a simple output showing the issue and an example of the Wizardry 1 intro screen.

Screen capture while FLASH is alternating black
![text-test-1](https://user-images.githubusercontent.com/63477279/79024345-a5f33100-7b50-11ea-8d33-8aa33b36e535.png)

Wizardry 1 
![Wizardy-1](https://user-images.githubusercontent.com/63477279/79024355-a986b800-7b50-11ea-9fec-a7b7907aef04.png)

**Comment by ThorstenBr** [comment]
Thanks for the report. Certainly related to my recent character ROM changes. I'll be looking into this...

**Comment by ThorstenBr** [comment]
Fixed by merge request #116. A simple issue. I had shifted the entire bitmap by one pixel with a recent commit, to exactly match the II/II+ character format. This incorrectly caused the first line of pixels in the second half of the bitmap (containing the "normal" character bitmaps) to be inverted.

**Comment by rhaleblian** [comment]
@ghost is it working for you now?

**Comment by rhaleblian** [comment]
If no-one else is seeing this, is it closable?

**Comment by ThorstenBr** [comment]
I have already fixed this. The issue was obvious. This can be closed. I'm unable to close this.
