### ISSUE TITLE
How does this thing find Master.dsk?

### ISSUE THREAD

**Issue by rhaleblian** [linappleii/linapple#120]
It's pretty amazing.
I'd say to use the XDG_* convention, as the configuration search logic is trying to do.
https://github.com/linappleii/linapple/pull/119
contains changes to search code that could have XDG mechanics inserted.

**Comment by rhaleblian** [comment]
If you run that PR, messages are printed showing new search process with all search path in one place. src/asset.cpp has a function showing it pretty clearly.
A great side-effect of the messages shows that Master.dsk is loaded four times at startup. That's thorough.

**Comment by rhaleblian** [comment]
More detail: since this is a data file, XDG_DATA_* is appropriate.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by nerun** [comment]
@maxolasersquad sorry for bothering you, but this one is very old and already resolved / merged, you can close this one. Maybe @rhaleblian could close himself.

Let's start closing issues? I noticed that there are a lot of them open and many resolved.

**Comment by rhaleblian** [comment]
What was the resolution?
