### ISSUE TITLE
Master.dsk

### ISSUE THREAD

**Issue by nerun** [linappleii/linapple#138]
Commit c93579f on May 26, 2020 have updated from version 2.1.1 to 2.2.1, but _Master.dsk_ version is still 2.1 from 28 Nov. 2017. Better update it.

Another thing: there are a lot of files that do exact the same thing inside Master.dsk:
* HELLO and, despite their names, SIREN, SOUNDTEST and SPLASH, do exactly the samething, better just keep HELLO and delete the others. The difference is that HELLO is TAB (12) and the others are TAB (9). SIREN is a broken binary, if you use Ciderpress and open it in HEX or RAW, you will see it is just a broken HELLO.
*  KEYS and KEYS1 are equal files, just delete KEYS1. But they are useless, better remove both.
* MYHELLO and AA are useless: the first prints numbers, the sencond just say ""Hello... I am Apple... GLAD TO MEET YOU, MY FRIEND". Really don't needed.

My suggestion is to remove all files and leaves an updated HELLO. Master disk should be a guidebook to LinApple!

**Comment by Nerun** [comment]
Here my custom [Master.dsk.zip](https://github.com/linappleii/linapple/files/5906964/Master.dsk.zip)

**Comment by nerun** [comment]
This was merged, closing.
