### ISSUE TITLE
Shift+F2 broken!

### ISSUE THREAD

**Issue by Nerun** [linappleii/linapple#140]
Shift+F2 should be "Reload configuration file and cold reboot". But instead it crashes!

ERROR MESSAGE:
`linapple: src/Applewin.cpp:867: void LoadAllConfigurations(const char*): Assertion '!registry' failed.`
`Aborted`

AND HERE MY TERMINAL:
![terminal](https://user-images.githubusercontent.com/3987342/83310146-79b77080-a1e1-11ea-9da0-a52273362e62.png)

**Comment by ThorstenBr** [comment]
Duplicate. See #100.
