### ISSUE TITLE
Compile fails with make: *** [Makefile:131: build/obj/charset40_british.xpm] Error 127

### ISSUE THREAD

**Issue by 2play** [linappleii/linapple#143]
hi gents @maxolasersquad @iKarith 

convert -flatten "res/charset40_british.png" "build/obj/charset40_british.xpm"
/bin/sh: 1: convert: not found
make: *** [Makefile:131: build/obj/charset40_british.xpm] Error 127

Any tips please?

**Comment by ThorstenBr** [comment]
Install ImageMagick.

**Comment by 2play** [comment]
> ImageMagick

@ThorstenBr Much appreciated! That did the trick
