### ISSUE TITLE
charset png -> xpm fails 

### ISSUE THREAD

**Issue by Ntemis** [linappleii/linapple#144]
http://dpaste.com/360XBVV

**Comment by nerun** [comment]
@maxolasersquad, no thing here too! LOL

**Comment by Ntemis** [comment]
pasted more than one year ago. sorry i dont pay for my own pastebin services just to keep it up for you guys

**Comment by maxolasersquad** [comment]
@Ntemis Are you willing to recreate the issue you experienced with the latest `master` branch and create a new pastebin?
