### ISSUE TITLE
It doesnt' work!

### ISSUE THREAD

**Issue by rickan54** [linappleii/linapple#146]
First, the version I downloaded from https://beotiger.com/download/linapple_src-2b worked out of the box as promised.

This version built fine but it does not run. INSTALL.md is WRONG about how to run it if not installed globally. Whether installed globally or not everything it doesn't do it claims the registry is read-only or other registry problem. No matter what I get a crash with a line of hex on the screen and an * prompt, e.g.:

0104-   a=D0 X=60 Y=08 P=35 S=FA
*

The beotiger version runs the Master.dsk from this version just fine.
The beotiger version runs sabotage just fine but this version crashes on it.

Ctrl-F2 is a BAD choice on Ubuntu-Studio. By default it switches to workspace #2.

$ uname -a
Linux rickan-Precision-5510 4.15.0-117-lowlatency #118~16.04.1-Ubuntu SMP PREEMPT Sun Sep 6 00:18:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I just wanted to run Space Eggs and I'm just about to the point of giving up.

Without F3

Selected machine type: Enhanced Apple //e Emulator
Joystick 1 Index # = 0, Name = (null) 
Button 1 = 0, Button 2 = 1 
Axis 0 = 0,Axis 1 = 1
[debug] Searching: . for Master.dsk
[info ] Master disk: ./Master.dsk
Disk is inserted. Full name = ./Master.dsk
Ready login = anonymous:mymail@hotmail.com
Selected machine type: Enhanced Apple //e Emulator
Joystick 1 Index # = 0, Name = (null) 
Button 1 = 0, Button 2 = 1 
Axis 0 = 0,Axis 1 = 1
Selected keyboard type: US
[debug] Searching: . for Master.dsk
[info ] Master disk: ./Master.dsk
Disk is inserted. Full name = ./Master.dsk
Ready login = anonymous:mymail@hotmail.com
Selected machine type: Enhanced Apple //e Emulator
Selected keyboard type: US
Keyboard rocker switch: standard/US charset
[debug] Searching: . for Master.dsk
[info ] Master disk: ./Master.dsk
Disk is inserted. Full name = ./Master.dsk
Ready login = anonymous:my-mail@mail.com
Screen size is 1120x768
bufferSize=00002000 bufferIdxMask=00001fff
SDL_MIX_MAXVOLUME=128
Freq=44100,format=32784,channels=2,silence=0
samples=512,size=2048,bufferSize=8192
Charset supports a second language: NO

F3 with sabotage.dsk

Selected machine type: Enhanced Apple //e Emulator
Joystick 1 Index # = 0, Name = (null) 
Button 1 = 0, Button 2 = 1 
Axis 0 = 0,Axis 1 = 1
[debug] Searching: . for Master.dsk
[info ] Master disk: ./Master.dsk
Disk is inserted. Full name = ./Master.dsk
Ready login = anonymous:mymail@hotmail.com
Selected machine type: Enhanced Apple //e Emulator
Joystick 1 Index # = 0, Name = (null) 
Button 1 = 0, Button 2 = 1 
Axis 0 = 0,Axis 1 = 1
Selected keyboard type: US
[debug] Searching: . for Master.dsk
[info ] Master disk: ./Master.dsk
Disk is inserted. Full name = ./Master.dsk
Ready login = anonymous:mymail@hotmail.com
Selected machine type: Enhanced Apple //e Emulator
Selected keyboard type: US
Keyboard rocker switch: standard/US charset
[debug] Searching: . for Master.dsk
[info ] Master disk: ./Master.dsk
Disk is inserted. Full name = ./Master.dsk
Ready login = anonymous:my-mail@mail.com
Screen size is 1120x768
bufferSize=00002000 bufferIdxMask=00001fff
SDL_MIX_MAXVOLUME=128
Freq=44100,format=32784,channels=2,silence=0
samples=512,size=2048,bufferSize=8192
Charset supports a second language: NO
Attempt to set 'Slot 6 Directory' to '/home/rickan/linapple' ignored (registry is read-only)
Disk is inserted. Full name = /home/rickan/linapple/sabotage.dsk
Attempt to set 'Disk Image 1' to '/home/rickan/linapple/sabotage.dsk' ignored (registry is read-only)

Using Shift-F2 instead of Ctrl-F2

Selected machine type: Enhanced Apple //e Emulator
Joystick 1 Index # = 0, Name = (null) 
Button 1 = 0, Button 2 = 1 
Axis 0 = 0,Axis 1 = 1
[debug] Searching: . for Master.dsk
[info ] Master disk: ./Master.dsk
Disk is inserted. Full name = ./Master.dsk
Ready login = anonymous:mymail@hotmail.com
Selected machine type: Enhanced Apple //e Emulator
Joystick 1 Index # = 0, Name = (null) 
Button 1 = 0, Button 2 = 1 
Axis 0 = 0,Axis 1 = 1
Selected keyboard type: US
[debug] Searching: . for Master.dsk
[info ] Master disk: ./Master.dsk
Disk is inserted. Full name = ./Master.dsk
Ready login = anonymous:mymail@hotmail.com
Selected machine type: Enhanced Apple //e Emulator
Selected keyboard type: US
Keyboard rocker switch: standard/US charset
[debug] Searching: . for Master.dsk
[info ] Master disk: ./Master.dsk
Disk is inserted. Full name = ./Master.dsk
Ready login = anonymous:my-mail@mail.com
Screen size is 1120x768
bufferSize=00002000 bufferIdxMask=00001fff
SDL_MIX_MAXVOLUME=128
Freq=44100,format=32784,channels=2,silence=0
samples=512,size=2048,bufferSize=8192
Charset supports a second language: NO
linapple: src/Applewin.cpp:867: void LoadAllConfigurations(const char*): Assertion `!registry' failed.
[1]+  Aborted                 (core dumped) linapple
$

**Comment by maxolasersquad** [comment]
This is caused by #32. Go ahead and checkout c93579fc7e71d3bd339079338cd9b2f05916828c and it should work fine.

```sh
git checkout c93579fc7e71d3bd339079338cd9b2f05916828c
```
