### ISSUE TITLE
--conf doesn't work

### ISSUE THREAD

**Issue by savetz** [linappleii/linapple#151]
When I invoke linapple with the --conf option, I get:

$ ./linapple --conf linapple.conf 
./linapple: invalid option -- '-'
./linapple: invalid option -- 'c'
./linapple: invalid option -- 'o'
./linapple: invalid option -- 'n'

**Comment by webspacecreations** [comment]
No a maintainer / contributor, but I haven't seen that problem with the latest build. Threw together some instructions to address breaking change from June: https://github.com/linappleii/linapple/issues/152

**Comment by Nerun** [comment]
> Not a maintainer / contributor, but I haven't seen that problem with the latest build. Threw together some instructions to address breaking change from June: #152

Yeah, it works for me.

**Comment by nerun** [comment]
@maxolasersquad another one to close ;-)
@savetz?
