### ISSUE TITLE
Merlin-8 breaks since 9cd7e5f

### ISSUE THREAD

**Issue by leesaudan2** [linappleii/linapple#159]
Merlin-8 no longer works since 9cd7e5fd968de96c5d223d0ffe286dea3e487acf.  I'm thrown into the monitor.  Here is how to reproduce it with Merlin-8 v2.48 for DOS 3.3:

1. Fetch the disk image https://archive.org/download/Merlin-8_v2.48_DOS_3.3/Merlin-8_v2.48_DOS_3.3.dsk
2. Boot that disk with enhanced //e emulation.
3. When the menu shows up, press "E" to enter the editor.
Now, you would see:
```
Editor

D102-    A=87 X=FF Y=00 P=F0 S=FB
*
```
You're thrown into the monitor.  You can go back to the menu with Ctrl-C ENTER.  But that does not fix anything.

Expected behaviour:
```
****************************************************************
Editor

:
```
with this `:` prompt waiting for editor commands.

There is a similar problem with Merlin-8 v2.58 for ProDOS.  The image is available here: https://archive.org/download/Merlin-8_v2.58_ProDOS_Disk_1-2/Merlin-8_v2.58_ProDOS_Disk_1-2.dsk
With this, you're thrown into the monitor directly upon booting.  Not even the main menu is reached.

These disks both work in  [gsport](/david-schmidt/gsport) (as of [7e78818](/david-schmidt/gsport/commit/7e788187b2d7b13e7b30cb52c6d76265bdba1b7b)).

**Comment by leesaudan2** [comment]
#148 fixes issue.

**Comment by akhepcat** [comment]
Have you tried this with the latest commits as of today?   The emulator is much more stable.

**Comment by leesaudan2** [comment]
> Have you tried this with the latest commits as of today? The emulator is much more stable.

Yes, it works now with b3771f866331fb5d926fd34493429d88c856a525.

Thanks
