### ISSUE TITLE
Replace TEXT macro with L

### ISSUE THREAD

**Issue by maxolasersquad** [linappleii/linapple#16]
Would it be beneficial, or even correct, to use the L macro instead of TEXT for string literals? If my reading is correct, the TEXT macro is something that comes from Microsoft and is only useful if you want to support unicode and non-unicode platforms.

**Comment by iKarith** [comment]
We don't actually have the L macro defined in wincompat.h, and ultimately TEXT() is a no-op on Linux.  Actually a lot of these Windows-specific types … again I'm somewhat torn because we can just use standard C/C++ types, but we decrease our diffability with AppleWin by doing so.

**Comment by maxolasersquad** [comment]
I'll go ahead and close this out. Such a change doesn't really affect anything.

**Comment by iKarith** [comment]
We could probably just remove the TEXT() all together.  Just wondering, do you use slack or discord?  One of the things I find kinda annoying about git is that it doesn't really give you a way to have discussions that don't directly relate to issues or pull requests (like this comment…)

**Comment by maxolasersquad** [comment]
Discord would probably be best.

**Comment by iKarith** [comment]
I use both—I know I can tie Github into Slack (and have done so on
apple2infinitum), but I do like the voice chat options with discord once in
awhile.  I personally can't use discord mobile, but that's not usually a
problem.

Joseph

**Comment by maxolasersquad** [comment]
I don't have much of a preference tbh.
