### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by sellam-i** [linappleii/linapple#161]
I'm getting an error when trying to install linapple.  I'm following the instructions here: 

https://github.com/linappleii/linapple/blob/master/INSTALL.md

The problem is occuring when I try to "sudo git clone git@github.com:linappleii/linapple.git" (see capture below).

I don't understand the response I'm getting and what I should do from here.  Any help would be appreciated.

Thank you.

Sellam

sellam@sellam-OptiPlex-7010:~/linapple$ sudo git clone git@github.com:linappleii/linapple.git 
[sudo] password for sellam:             
Cloning into 'linapple'...
The authenticity of host 'github.com (192.30.255.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
sellam@sellam-OptiPlex-7010:~/linapple$ sudo git clone git@github.com:linappleii/linapple.git 
Cloning into 'linapple'...
The authenticity of host 'github.com (192.30.255.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,192.30.255.113' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
sellam@sellam-OptiPlex-7010:~/linapple$ sudo git clone git@github.com:linappleii/linapple.git 
Cloning into 'linapple'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
sellam@sellam-OptiPlex-7010:~/linapple$

**Comment by bodhi-baum** [comment]
Seems that the RSA key is not right / recognized.

**Comment by leesaudan2** [comment]
You don't need `sudo` for cloning the repository.

**Comment by Nerun** [comment]
Easy way:
<code>git clone https://github.com/linappleii/linapple.git</code>

**Comment by sellam-i** [comment]
> Easy way:
> `git clone https://github.com/linappleii/linapple.git`
> 
> And NO SUDO as explained @leesaudan2

Ok, I did this.  Did "make", got a lot of compiler warnings.  It completed with no errors, but when I run the resulting linapple I get a segmentation fault.

This shouldn't be difficult.  I installed linapple on my old computer many years ago and it was effortless.  Why can nothing be simple anymore?  What the hell happened to the linux community?

**Comment by leesaudan2** [comment]
> Ok, I did this. Did "make", got a lot of compiler warnings. It completed with no errors, but when I run the resulting linapple I get a segmentation fault.
> 
> This shouldn't be difficult. I installed linapple on my old computer many years ago and it was effortless. Why can nothing be simple anymore? What the hell happened to the linux community?

On what architecture are you?  64-bit?  What's the output of `uname -a`?

**Comment by Nerun** [comment]
uname -a
<code>Linux debian 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux</code>

Did you installed dependencies?
<code>sudo apt-get install git libzip-dev libsdl1.2-dev libsdl-image1.2-dev libcurl4-openssl-dev zlib1g-dev</code>

**Comment by bodhi-baum** [comment]
I also assume that there are dependenies missing. When I installed linapple a few weeks ago at a Linux Mint, everythin went well.

**Comment by sellam-i** [comment]
I've confirmed the dependencies are installed.

uname -a

Linux sellam-OptiPlex-7010 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Here's an example of the compiler warnings I'm getting:

`In file included from /usr/include/stdio.h:867,
                 from inc/stdafx.h:12,
                 from src/DiskFTP.cpp:16:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 2 or more bytes (assuming 772) into a destination of size 260
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
g++ -Wall -O3 -ansi -c -std=c++11 -DASSET_DIR=\"share/linapple\" -DVERSIONSTRING=\"2.2.1\" -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -Wno-write-strings -Iinc -I/usr/local/include -c -o build/obj/Applewin.o src/Applewin.cpp
g++ -Wall -O3 -ansi -c -std=c++11 -DASSET_DIR=\"share/linapple\" -DVERSIONSTRING=\"2.2.1\" -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -Wno-write-strings -Iinc -I/usr/local/include -c -o build/obj/Log.o src/Log.cpp
g++ -Wall -O3 -ansi -c -std=c++11 -DASSET_DIR=\"share/linapple\" -DVERSIONSTRING=\"2.2.1\" -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -Wno-write-strings -Iinc -I/usr/local/include -c -o build/obj/Disk.o src/Disk.cpp
src/Disk.cpp: In function ‘void DiskSelectImage(int, LPSTR)’:
src/Disk.cpp:646:38: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
  646 |   snprintf(tempPath, MAX_PATH, "%s/%s", fullPath, filename); // Next dir
      |                                      ^
In file included from /usr/include/stdio.h:867,
                 from inc/stdafx.h:12,
                 from src/Disk.cpp:33:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 2 or more bytes (assuming 261) into a destination of size 260
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/Disk.cpp:632:46: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
  632 |           snprintf(tempPath, MAX_PATH, "%s/%s", fullPath, filename); // next dir
      |                                              ^
In file included from /usr/include/stdio.h:867,
                 from inc/stdafx.h:12,
                 from src/Disk.cpp:33:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 2 or more bytes (assuming 261) into a destination of size 260
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/Disk.cpp: In function ‘void Disk_FTP_SelectImage(int)’:
src/Disk.cpp:731:38: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
  731 |   snprintf(tempPath, MAX_PATH, "%s/%s", fullPath, filename);
      |                                      ^
In file included from /usr/include/stdio.h:867,
                 from inc/stdafx.h:12,
                 from src/Disk.cpp:33:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output 2 or more bytes (assuming 261) into a destination of size 260
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by leesaudan2** [comment]
> I've confirmed the dependencies are installed.
> 
> uname -a
> 
> Linux sellam-OptiPlex-7010 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> 
> Here's an example of the compiler warnings I'm getting (I cut and pasted a section from the output, there are several more pages of similar warnings):

... [snipped]

That means you've got no errors, just some warnings?  Then, you've compiled it successfully.  To confirm, just try running `make` again.  If it finishes without doing anything, the compilation is successful.

**Comment by sellam-i** [comment]
> > I've confirmed the dependencies are installed.
> > uname -a
> > Linux sellam-OptiPlex-7010 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> > Here's an example of the compiler warnings I'm getting (I cut and pasted a section from the output, there are several more pages of similar warnings):
> 
> ... [snipped]
> 
> That means you've got no errors, just some warnings? Then, you've compiled it successfully. To confirm, just try running `make` again. If it finishes without doing anything, the compilation is successful.

Oh, right.  I forgot to mention that when I run linapple it immediately crashes with a "segmentation fault" and core dump.

sellam@sellam-OptiPlex-7010:~/linapple$ linapple
Selected machine type: Enhanced Apple //e Emulator
Joystick 1 Index # = 0, Name = (null) 
Button 1 = 0, Button 2 = 1 
Axis 0 = 0,Axis 1 = 1
[debug] Searching: . for Master.dsk
[debug] Searching: share/linapple for Master.dsk
[debug] Searching: /home/sellam/.local/share/linapple for Master.dsk
[debug] Searching: /usr/local/share/linapple for Master.dsk
[info ] Master disk: /usr/local/share/linapple/Master.dsk
Disk is inserted. Full name = /usr/local/share/linapple/Master.dsk
Ready login = anonymous:mymail@hotmail.com
Selected machine type: Enhanced Apple //e Emulator
Joystick 1 Index # = 0, Name = (null) 
Button 1 = 0, Button 2 = 1 
Axis 0 = 0,Axis 1 = 1
Selected keyboard type: US
[debug] Searching: . for Master.dsk
[debug] Searching: share/linapple for Master.dsk
[debug] Searching: /home/sellam/.local/share/linapple for Master.dsk
[debug] Searching: /usr/local/share/linapple for Master.dsk
[info ] Master disk: /usr/local/share/linapple/Master.dsk
Disk is inserted. Full name = /usr/local/share/linapple/Master.dsk
Ready login = anonymous:mymail@hotmail.com
Screen size is 560x384
bufferSize=00002000 bufferIdxMask=00001fff
SDL_MIX_MAXVOLUME=128
Freq=44100,format=32784,channels=2,silence=0
samples=512,size=2048,bufferSize=8192
Segmentation fault (core dumped)

Sum ting wong.

**Comment by sellam-i** [comment]
BUMP

**Comment by sellam-i** [comment]
I'm giving up on this, and giving up on linapple altogether.  I'll instead (reluctantly) install a Windows emulator and just run WinApple, and wait for the multiplatform version of WinApple to get released.  In fact, I think I will contribute to that project, as this one seems dead.

**Comment by xandark** [comment]
Just a FYI, this has all been resolved in #166 -- it's so much better now with compiling and the instructions are much clearer.
