### ISSUE TITLE
INSTALL.md has outdated information that is tripping up newbies

### ISSUE THREAD

**Issue by xandark** [linappleii/linapple#166]
I'm trying to help with issue #161 by doing a fresh build of Linapple. I was able to build it, but I found that the instructions in https://github.com/linappleii/linapple/blob/master/INSTALL.md were incorrect and could confuse someone new to the project.

In the Clone step, it says:

`git clone git@github.com:linappleii/linapple.git`

... but that will give a response that I've seen confuse newbies (who just want to get this working):

```
Cloning into 'Linapple'...
The authenticity of host 'github.com (140.82.112.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

Instead, it'd be easier and avoid confusion to ask the users to do this:

`git clone https://github.com/linappleii/linapple.git`

Using the https URL is also the default clone option that Github in their web UI. 

Regarding the "Compile" step, the compilation spits out a lot of warnings at a fast pace, which is alarming to newbies. It's not even clear that they're warnings because the messages are so long and the word "warning" is buried. Can this step mention, "don't worry about spurious warning messages, which can look like errors; chances are that the program will build successfully with the errors". That would go a long way to reassuring people.

Regarding the "Global Install" step, can we mark that as optional? Moving the binary off into a protected part of the OS is one more indirection that can confuse newbies, especially when the newly built binary is right in front of them.

For the "Run" step, can we insert something like this that would make it simple and easy to understand and test?:

```
cd build/bin
./linapple --autoboot --d1 ../share/linapple/Master.dsk
```

That way the binary can be checked immediately.

As it turns out in my case, by doing that Linapple crashes to the monitor after trying to boot. This is what I'm seeing no matter which .dsk or .po image I put in drive 1:

![Screenshot 2021-02-20 (18∶18∶44)](https://user-images.githubusercontent.com/5048913/108613572-1e00c900-73a8-11eb-9b64-577a5da0318a.png)

(Should that be opened as a new issue? Running up-to-date KDE neon 20.04.)

Regarding the "Configure" step, it says,

`A directory name linapple can be found in your home directory. Edit the linapple.conf file.`

That does not seem to be true any longer. I found it at ~/.config/linapple/linapple.conf.  It would be nice if it mentioned explicitly that the linapple.conf.sample file in the root of the project can be copy/paste'd into ~/.config/linapple/linapple.conf.

**Comment by captaincafeman** [comment]
I'm having the same issue with Linapple crashing to monitor regardless of which .dsk image I try as well. Have tried multiple from Asimov as well this ProDOS dsk image and all exhibit the same behaviour:

https://archive.org/download/ProDOS_2_4_1/ProDOS_2_4_1.dsk

However, editing the linapple.conf file in ~/linapple was the only way I could make my settings work. Editing the file in ~/.config/linapple didn't work for me.

**Comment by captaincafeman** [comment]
For those interested in using this on a Raspberry Pi, installing the linapple packages sourced by RetroPie seems to work. Compiling from this source on Raspbian creates a binary that runs but fails to load DSK and DO files as per above.

**Comment by akhepcat** [comment]
FYI, the crash at boot should now be resolved as PR 169 has been merged into mainline.

**Comment by nerun** [comment]
Regarding issue #161, it was fixed by PR #164, merged into mainline today.

**Comment by xandark** [comment]
I pulled the latest version of Linapple and I'm getting compile errors:

```
$ make
g++ -Wall -O3 -ansi -c -std=c++11 -DASSET_DIR=\"share/linapple\" -DVERSIONSTRING=\"2.2.1\" -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT  -Wno-write-strings -Iinc -I/usr/local/include -c -o build/obj/CPU.o src/CPU.cpp
src/CPU.cpp: In function ‘DWORD Cpu65C02(DWORD)’:
src/CPU.cpp:870:29: error: ‘FALSE’ was not declared in this scope
  870 |   BOOL bSlowerOnPagecross = FALSE;    // Set if opcode writes to memory (eg. ASL, STA)
      |                             ^~~~~
src/CPU.cpp: In function ‘DWORD Cpu6502(DWORD)’:
src/CPU.cpp:2166:29: error: ‘FALSE’ was not declared in this scope
 2166 |   BOOL bSlowerOnPagecross = FALSE;    // Set if opcode writes to memory (eg. ASL, STA)
      |                             ^~~~~
make: *** [Makefile:129: build/obj/CPU.o] Error 1

```

Where is FALSE delcared?

**Comment by akhepcat** [comment]
it's not.   change them to   lowercase.    ("false")

**Comment by xandark** [comment]
I'll just wait until the change is committed, but thanks.

**Comment by akhepcat** [comment]
This makes for a quick revert, if you get bored waiting

```
sed -i.bak 's/FALSE/false/g;' src/CPU.cpp
git diff > CPU.diff
make
patch -p1 -R < CPU.diff

```

**Comment by xandark** [comment]
This PR makes the code much easier to compile. There's still a gnarly warning compiling DiskFTP.cpp, but much better all around. I notice that Ctrl-F2 doesn't do anything; pressing F7 to switch into the debugger on the 2nd time results in glyphs that are garbled and then it crashes when pressing F7 to switch out; Shift-F2 causes a crash (linapple: src/Applewin.cpp:874: void LoadAllConfigurations(const char*): Assertion `!registry' failed.); and the text on the F1 help screen is difficult to read because the glyphs are stretched without anti-aliasing. Should these be a new issue?

**Comment by akhepcat** [comment]
the warning in DiskFTP is just that - a warning - that can be (mostly) ignored.   It's only because the compiler doesn't know how to validate the length of the potential strings, but it's really not critical because snprintf will truncate correctly.   It's possible to "trick" the compiler into shutting up by passing the string length as another parameter, as in  src/Frame.cpp:

`snprintf(fpath, MAX_PATH, "%.*s/SaveState%d.aws", int(strlen(g_sSaveStateDir)), g_sSaveStateDir, num); `

while this type of workaround isn't *necessary* , disabling the warning means you lose visibility into *actual* string overruns.

--

As for the rest,  yes, you should create new issues, as you're referencing a new build.   Make sure to include your OS info as well, as sometimes that's a factor in tracking down the culprits.

**Comment by akhepcat** [comment]
FWIW,  a clean build on my Linux (kubuntu 21.04)  doesn't exhibit the issues with ctrl-F2  (reboot works)   and  F7  (in/out debugger works multiple times, no graphics corruption)

Shift-F2  does crash for me as well, so when you create your issue  (do a make clean; git pull; make; build/bin/linapple --autoboot --d1 build/share/linapple/Master.dsk - or equivalent,  first, and validate your issues from a fully cleaned build)  i'll second it.  

cheers

**Comment by xandark** [comment]
Okay I think we can mark this is closed, very good!

**Comment by xandark** [comment]
P.S. Ctrl-F2 is a default system shortcut on the latest KDE Plasma to "switch to Desktop 2". So no issue with Linapple.
