### ISSUE TITLE
PR 154 incorrectly uses  FALSE instead of 'false'

### ISSUE THREAD

**Issue by akhepcat** [linappleii/linapple#172]
Just tried a quick
git pull && make

and then get this:

src/CPU.cpp: In function ‘DWORD Cpu65C02(DWORD)’:
src/CPU.cpp:870:29: error: ‘FALSE’ was not declared in this scope
870 | BOOL bSlowerOnPagecross = FALSE; // Set if opcode writes to memory (eg. ASL, STA)
| ^~~~~
src/CPU.cpp: In function ‘DWORD Cpu6502(DWORD)’:
src/CPU.cpp:2166:29: error: ‘FALSE’ was not declared in this scope
2166 | BOOL bSlowerOnPagecross = FALSE; // Set if opcode writes to memory (eg. ASL, STA)
| ^~~~~
make: *** [Makefile:129: build/obj/CPU.o] Error 1

FALSE is not defined in any files within the project.

those should probably be lower-case'd to comply with the standard conventions

**Comment by nerun** [comment]
This was [merged today](https://github.com/linappleii/linapple/commit/d9abef185800b960272285722372a855b3c66edc), but `CPU.cpp` failed to compile. To fix it change: `FALSE` to `false` in lines 870 and 2166.

**Comment by akhepcat** [comment]
FALSE is a win32/64 macro, to be equivalent to the win32/64  'c'  macro

false is the c++ standard equivalent everywhere.

Since the source is portable c++,  folk submitting patches need to be wary of including OS-specific defines, and use the standards where available.    Only where there are conflicts should there be workarounds (e.g., "wincompat.h")

**Comment by akhepcat** [comment]
latest commit 56bfa4020f0c41499704958fe01824c421704ef6  (based on above) resolves the error
