### ISSUE TITLE
Write protected disks

### ISSUE THREAD

**Issue by Dogdive** [linappleii/linapple#197]
Hello. Is there a way to write protect a .dsk? Games such as Wizardry need the boot disk to act like it is write protected or it stalls after the title sequence and fails to load. Just curious.

**Comment by lowlevel-1989** [comment]
> Hello. Is there a way to write protect a .dsk? Games such as Wizardry need the boot disk to act like it is write protected or it stalls after the title sequence and fails to load. Just curious.

yes, it is done at the s.o level, with the following command:
$ chmod a-w file.dsk

**Comment by Dogdive** [comment]
Sweet. Thank you.
