### ISSUE TITLE
BSD portability: Don't use obj/

### ISSUE THREAD

**Issue by iKarith** [linappleii/linapple#21]
Our use of a directory named `obj` is incompatible with BSD's make.  We don't presently explicitly support building on BSD, and we wouldn't be the first project to require the use of GNU make on that platform if we did.  [This page](https://www.gnu.org/software/autoconf/manual/autoconf-2.67/html_node/obj_002f-and-Make.html) describes one of the major gotchas.

This can all be solved with the use of autoconf and possibly automake (at the potential cost of my sanity in porting it—something I've already started doing, God help me).  Until that's done, I'm just documenting the issue.

**Comment by ghedger** [comment]
Sorry about that.  It's a very old practice that predates modern conventions.

**Comment by ghedger** [comment]
Okay, changed to "build".

**Comment by rhaleblian** [comment]
PR is posted.
