### ISSUE TITLE
Ramworks (aux) bank emulation bug

### ISSUE THREAD

**Issue by jbevren** [linappleii/linapple#34]
The banked auxiliary memory (aka ramworks) emulation is somewhat flawed.  To demonstrate the flaw follow these steps from a linux command line:

`user:~ $ linapple -r4 #enable ramworks emulation`

Within linapple at any basic prompt with or without a DOS:
```
] pr#3
] call -151
* c073:1
```

At this point the odd columns (1,3,5...79) fetched from aux memory are updated with zeros (inverse @).  On real hardware video memory is always fetched from aux bank 0 so there would be no visual difference, but the emulated hardware immediately updates the columns stored in auxiliary memory with nulls upon bank switch.

This causes visual flashes and glitches while running programs that use banked auxiliary memory such as appleworks =>3.0.

As a secondary and likely related issue after switching the aux bank to !=0 the 80 column firmware (incorrectly) successfully updates the display.  This should not be the case as real hardware still scans aux bank 0 while the firmware will write to the currently selected bank.  Thus video updates will only affect the even columns (0,2,4...78).

I'd provide a patch but I'm unable to grok where the video and aux bank handling is in the code.  Additional assistance is available to help resolve the issue.

(edit: removed a typo)

**Comment by jbevren** [comment]
Issue is located and corrected in pull 35.

**Comment by maxolasersquad** [comment]
Merged #35
