### ISSUE TITLE
Saving a apple ii basic code 

### ISSUE THREAD

**Issue by eranfeit** [linappleii/linapple#55]
Hi,
How do I save and load basic code written in the emulator ?

Thank you 
Eran

**Comment by maxolasersquad** [comment]
You will need to save it to a virtual disk.

**Comment by rhaleblian** [comment]
Loading code is a bit hairy as it has to be on a disk image as well.
I write code directly into a running emulator and save it to the inserted disk.
That's how it was back in the day.

**Comment by rhaleblian** [comment]
This seems closable.

**Comment by maxolasersquad** [comment]
Agreed.
