### ISSUE TITLE
Why does it not load .dsk files?

### ISSUE THREAD

**Issue by Rak355** [linappleii/linapple#57]
Attempt to set 'Disk Image 1' to '/home/user/Desktop/linapple/res/Master.dsk' ignored (registry is read-only)

**Comment by taeber** [comment]
@Rak355, could you try again? I believe the typo fixed with PR #61 might have caused your issue.

**Comment by taeber** [comment]
I did some testing with the code before and after my changes. Throughout all changes, I have been able to load disk images. I believe the warning about the "registry" being read-only has been there since the original fork and is unrelated.

Is anyone else having trouble loading .DSK files?

**Comment by ghedger** [comment]
No, not on this official repo version.

**Comment by rhaleblian** [comment]
No problems. IME and IIUC, the registry message is benign. Message should be removed if possible.

**Comment by hiroyukif** [comment]
This issue has not been resolved.
Debian Linux:Why does it not load.dsk files?
