### ISSUE TITLE
Bank switching in High RAM / misuse of AltZP

### ISSUE THREAD

**Issue by tomcw** [linappleii/linapple#96]
I saw in #8 ([here](https://github.com/linappleii/linapple/issues/8#issuecomment-499609176)), that @ghedger said:

>Other topic: There is an ongoing bug in AppleWin, and thus LinApple, relating to bank switching in High RAM -- these are the $C08x switches. AppleWin is (mis)using the AltZP as a switch for this in a long, complex logic statement. It's been a few months or I'd be more specific. Anyways, it's a case where it "works" for most software, since using the two upper banks of LCRAM in combination with the AltZP was apparently not common, but is nevertheless something I'd like to take a look at when I'm not embroiled in paying projects.

Can you provide some details how to repro this issue?

**Comment by ghedger** [comment]
Hello Sir Tom,

Great to hear from you again.  Recall we collaborated on Mockingboard emulation about 15 years ago.

It's not a problem of the form "xyz program doesn't run".  Rather, it's derived from the text http://www.applelogic.org/files/AIIETECHREF2.pdf pages 79 onward in the actual manual, page 9 of the PDF.   Page 85 is interesting.  Page 87 is the most relevant.

Essentially it centers around use of the alternate (AUX) zero-page.  I don't believe this was a popular feature, but if you're program is running in $D000-$FFFF you can, in theory, switch between two zero pages.

I really need to set up my Apple IIe to test this out, but that's how I am reading the technical manual -- and what I actually wanted to take advantage of in an Apple II game I've been writing...

**Comment by tomcw** [comment]
Hi Greg,

Good to chat to you again too!

>but if your program is running in $D000-$FFFF you can, in theory, switch between two zero pages.

Yes... but because high RAM (ie. Bank Switched RAM or Language Card RAM) is enabled, then changing ALTZP means that you'll need the same code in both main & aux Bank Switched RAM.

EG. (using the notation: 64K-bank/16-bit addr)
- ; have the same code copied to both 0/D000-FFFF and 1/D000-FFFF
- PC=0/D000, SP=0/01nn
- set ALTZP
- PC=1/D003, SP=1/01nn
- clr ALTZP
- PC=0/D006, SP=0/01nn

See Sather (Understanding the IIe), page 5-25, where it starts "ALTZP..." for his explanation and 4 scenarios (although none of which apply to your specific case).

Best to set up your IIe and write your own tests. I'm interested in whatever results you get.

**Comment by ghedger** [comment]
@tomcw You're probably correct and I'm full of bollocks.  I'm using the ZP -- a big chunk of it, like $80 bytes or more -- for "fast" (by 8-bit Apple II standards) sprite blitting in Double HiRes but in an Ultima-style RPG.  Having Alt-ZP for this functionality is not strictly necessary, but a nice-to-have.  Test of course is whether a real Apple II can do this -- maybe it can, maybe it cannot.

Thanks for the Sather reference.  I'll try to find that.

You are right about the IIe.  I have the space now for it, just need to find an inexpensive VGA-compatible monitor...  Anyways, that's my problem to solve.

**Comment by ghedger** [comment]
[http://towelsnapper.com/data/AG_PRES.DSK](url)

Achterlanden, work-in-progress, a beautiful Double HiRes engine for 8-bit 128k Apple II.

**Comment by ghedger** [comment]
Here's the test:

![image](https://user-images.githubusercontent.com/3182704/76277616-db091c80-624e-11ea-8551-2b3c6f2fc5e9.png)

See the gray box immediately beneath the castle?  That's drawn with a sprite engine.  In our current LinApple code, that box (a sprite) is absent.

Code in our existing LinApple:

` for (loop = 0xD0; loop < 0xE0; loop++)
  {
    int bankoffset = (SW_BANK2 ? 0 : 0x1000);
    memshadow[loop] = SW_HIGHRAM ? SW_BANK2 ? memaux+(loop << 8)-bankoffset
                        : memmain+(loop << 8)-bankoffset
                  : memrom+((loop-0xD0) * 0x100);

    memwrite[loop]  = SW_WRITERAM  ? SW_HIGHRAM  ? mem+(loop << 8)
                            : SW_BANK2  ? memaux+(loop << 8)-bankoffset
                                  : memmain+(loop << 8)-bankoffset
                    : NULL;
  }
`

Code in a LinApple I had modified to produce the above image:
`
  for (loop = 0xD0; loop < 0xE0; loop++)
  {
    int bankoffset = (SW_BANK2 ? 0 : 0x1000);
    memshadow[loop] = SW_HIGHRAM ? SW_BANK2 ? memaux+(loop << 8)-bankoffset
                        : memmain+(loop << 8)-bankoffset
                  : memrom+((loop-0xD0) * 0x100);

    memwrite[loop]  = SW_WRITERAM  ? SW_HIGHRAM  ? mem+(loop << 8)
                            : SW_BANK2  ? memaux+(loop << 8)-bankoffset
                                  : memmain+(loop << 8)-bankoffset
                    : NULL;
  }
`

**The Acid test will be a real Apple IIe.**  If there's something esoteric in Sather (which  Again, I do not have a VGA-input LCD monitor, and I believe Apple II HDMI adapters are very expensive...  I will have to test this later, but I would think it's HIGHRAM would affect the high RAM, 

To make this go faster, someone else could download my disk image ("AG_PRES.DSK") above, ADT it over to an Apple IIe, and report the results.

Summary: it's lack of clarity about the treatment of the softswitches at $C012 and $C016...

Hope that helps!

**Comment by nlflint** [comment]
@ghedger Here's a video of me running it on an Apple IIe (un-enhanced), and a Rom 01 IIGS: https://www.youtube.com/watch?v=YPIk5Z_fiWQ

I can see the grey box on both, but it is moving. Should it be moving?

**Comment by ghedger** [comment]
I've set up a real Apple IIGS in the garage -- it should emulate the proper IIe behavior.  There are no 65C816 instructions in the codebase so I would consider that a fair test.  
A special serial-to-USB cable is on order for the disk transfer.
@tomcw

**Comment by ghedger** [comment]
@nlflint THANK YOU!  Yes it should!
@tomcw see nlfints's post above.  There is indeed a bug in both AppleWin and LinApple -- see the code comparison I shared above.

**Comment by ghedger** [comment]
@nlfint the wierder thing to me is why the occlusion tiles are black in the emulator, but solid white on your IIe and a checkered pattern on the GS.  All the more reason to get my own GS up and running...  That's very, very strange.
Thank you again...

**Comment by ghedger** [comment]
Fixed and merged in Linux.  Leaving open for now for the AppleWin side.

**Comment by tomcw** [comment]
@ghedger - that's _very_ interesting! I'll need to study and try this myself.

**Comment by ghedger** [comment]
For our notes...
![image](https://user-images.githubusercontent.com/3182704/76349793-4515d600-62d0-11ea-8a29-2bb34045caf2.png)

**Comment by ghedger** [comment]
Also for our notes:
![image](https://user-images.githubusercontent.com/3182704/76349904-7b535580-62d0-11ea-9bc0-fb97adb8b949.png)

It's not clear to me at this time where LinApple is handling the 
`LDA $C083`
`LDA $C083`
-type of operations.

Really need a more rigorous test besides "That fixed x program but now y program is broken".  Wonder what memory diagnostic software is available to us -- another thing to look into...

**Comment by ghedger** [comment]
![image](https://user-images.githubusercontent.com/3182704/76350345-2fed7700-62d1-11ea-9736-4235587a868b.png)

**Comment by ghedger** [comment]
Looks like Apple IIe Diagnostics v2.1 is our friend...

**Comment by ghedger** [comment]
Also found this:
![image](https://user-images.githubusercontent.com/3182704/76358763-9f6a6300-62df-11ea-85c6-3c65cecd6b3c.png)

This implies we cannot just use memaux for Bank 2 of $D000-DFFF.  If I'm understanding this aright there is the following:

$D000-$DFFF BANK 1, MAIN
$D000-$DFFF BANK 2, MAIN
$D000-$DFFF BANK 1, AUX
$D000-$DFFF BANK 2, AUX

That's perfectly logical, because it's the only way all 64k in both main and auxillary RAM would be accessible...

**Comment by tomcw** [comment]
That's right - all those 4 can reside at $D000-DFFF depending on MMU soft-switches... and ROM at that location is another option too.

>This implies we cannot just use memaux (defined in the emulators' source) for Bank 2 of $D000-DFFF.

From my notes in (AppleWin's) memory.cpp: (BSR = Bank Switched RAM)
```
// memmain, memaux
// - physical contiguous 64KB "backing-store" for main & aux respectively
// - NB. 4K bank1 BSR is at $C000-$CFFF
```

If you have the MMU using memaux (not memmain) then...

(1) assuming you set the LC switches (ie. $C08B to r/w RAM bank-1) correctly, then:
- for reading: the 4K of "Bank 1" gets memcpy()'d from `&memaux[0xC000]` to `&mem[0xD000]`
- for writing: `memwrite[0xDn] = &mem[0xDn00]`  (where n={0,..,F})

(2) assuming you set the LC switches (ie. $C083 to r/w RAM bank-2) correctly, then:
- for reading: the 4K of "Bank 2" gets memcpy()'d from `&memaux[0xD000]` to `&mem[0xD000]`
- for writing: `memwrite[0xDn] = &mem[0xDn00]`  (where n={0,..,F})

Anyway, I agree with what you said above about needing a rigorous test... and simple too!

**Comment by ghedger** [comment]
Your examples are somewhat helpful, Tom, as I've been trying to understand the proper relationship between `memmain`/`memaux` and `mem`

Going to write a program on a real Apple II to store 0x01, 0x02, 0x03, and 0x04 into the four respective $D000 locations and then read them and write the values out at memmain: $300,$301,$302,and $303.  If the program copies itself into AUX RAM (say org = $6000) it should be able to switch back and forth freely between main and AUX.  Verifying it actually works the way we think according to the documentation will help provide a starting point (or implicate my understanding for needed adjustment).

**Comment by ghedger** [comment]
@tomcw 
Testing on a real Apple II, I'm a little shocked, but it looks like you were right: there _is_ some relationship between the ALTZP and what is read from the respective $D000 locations.

Reading through the Sather reference you'd shared earlier to try to find where this is documented...

Head-scratcher...

**Comment by ghedger** [comment]
@tomcw You definitely got it right -- at least partly.  I'm not sure why.  I finally got output of 0x01 0x02 0x03 0x04 (inverse-ABCD) written to $428-$42B text page, after having written the four unique values to the four $D000s.  Instead of writing to READAUX ($C003) to read auxillary upper LC RAM, I had to write to AUXZP.  Again, this is on a real Apple II (a GS running emulation mode).

I think there is still a minor issue with switching the main and auxillary LC Bank 1s and Bank 2s; I need to port the little program I wrote to the emulator, something I will have to probably do by hand due to lack of a cable that's on order.

There's

**Comment by ghedger** [comment]
I do not think further action is warranted on this at this time.  The sprite drawing operation in my work-in-progress game was a masking operation.  I was unaware, at the time, of the tie between ALTZP and $D000-$DFFF access.  The sprite data, as this is a test sprite living embedded in the code, was stored in $DXXX.

The fact it showed up in some cases, in @nlflint 's Apple II tests, and didn't show up in LinApple, had to do with what happened to be in memory at the time -- and since it was a masking operation it's entirely possible that with the right combination of data nothing at all would show up.  The smoking gun clue lay in the fact @nlflint got different results on his IIe and IIGS -- which have different memory patterns at startup owing to different chip manufacturers for the DRAM (what's particularly weird is that it was the GS, not the IIe, that showed the checkerboard pattern; on my GS the memory is zeroed out on startup and on my IIe it's 00 00 FF FF).

@tomcw I am sorry to have troubled you with this unusual red herring problem.  If anything else related to this pops up I will re-open the issue.

**Comment by tomcw** [comment]
@ghedger - no problem... always happy to try to reason these MMU-related issues, and it's good to hear that this particular issue has been proven false.

IMO, the AppleWin / LinApple code for this is very obtuse, especially in `UpdatePaging()` and even more so in the innocuous looking `MemGetMainPtr()`! (I didn't write any of this code, btw)

I have made some attempts to document it here:
- memmain, memaux, memwrite, memshadow etc: https://github.com/AppleWin/AppleWin/blob/c2047838164f2fdf20c7bb68549245ba9c20e68e/source/Memory.cpp#L139
- MemGetMainPtr(): https://github.com/AppleWin/AppleWin/blob/c2047838164f2fdf20c7bb68549245ba9c20e68e/source/Memory.cpp#L1313

Any improvements or more sensible way of describing these memory arrays & functions is most welcome! :-)

**Comment by ThorstenBr** [comment]
So, not quite sure what the result of your discussion is: was the original change in
https://github.com/linappleii/linapple/commit/1debfda336dda19c6f1c09cf629d2dc9c800f246
unnecessary then - or was there still something to be fixed? Somehow this commit prevents some applications from running properly...

**Comment by ghedger** [comment]
Should be unnecessary.  Let me check if I'd merged the change back to the working version....

**Comment by ghedger** [comment]
Yes.  I had made the change and not checked it it.  It is now checked in to master.  Please let me know if there is anything else wrong.

**Comment by ThorstenBr** [comment]
Yes, seems all good now. Thanks! :)

**Comment by ThorstenBr** [comment]
@ghedger: Unfortunately there is still an issue. Seems the revert was accidentally only partial (see commit 0ce4b71334966da2285967cc9215a1a3a14b0395). Only the logic for the E0xx range (and up) was reverted. The same code/issue still applies to the D0xx-DFxx range. This was also broken by the commit discussed above - but was later not reverted for this address range.

Line 679 (in current head revision) still contains the "#if 0", which activates the new code. Games like GATO (submarine) or Karteka no longer load with this switch. I debugged it (with the new debugger :) ) and traced it to a loading routine which writes data to a RAM bank via a zero page pointer. With the new code, the data is no longer stored in the RAM bank. Also reverting the access logic for the D0... range (same revert as previously for the E0 range) fixes the issue:

```
  for (loop = 0xD0; loop < 0xE0; loop++) {
    int bankoffset = (SW_HRAM_BANK2 ? 0 : 0x1000);
#if 0
		memshadow[loop] = SW_HIGHRAM
												? SW_ALTZP
													?	memaux + (loop << 8) - bankoffset
													: memmain + (loop << 8) - bankoffset
												: memrom + ((loop - 0xD0) * 0x100);
```

=> "#if 0" there also needs to be reverted to "#if 1".

I'm going to push a merge request...
